"""Tests for the cookiecutter-rapyd-django template.

Tests bake the template into a temp directory and assert:
- The bake succeeds and the post-gen hook runs cleanly.
- All expected files are present; legacy files are absent.
- The generated project passes ruff and pytest.
- python_version and author fields render into pyproject.toml.
- The pre-gen hook rejects invalid slugs, emails, and unsafe chars.
- The post-gen hook fails gracefully when uv is missing from PATH.

Note: cookies.bake() runs the post-gen hook, which calls `git init` and
`uv sync`. Tests that call cookies.bake() require git, uv, and network
access. uv caches packages locally so only the first run downloads.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

# Strip parent-process venv/Python pins so uv commands in the generated project
# use the project's own .venv rather than the test runner's interpreter.
_ISOLATED_ENV = {
    k: v
    for k, v in os.environ.items()
    if k not in ("VIRTUAL_ENV", "VIRTUAL_ENV_PROMPT", "UV_PYTHON")
}

# Default slug derived from the default project_name "Django Boilerplate".
DEFAULT_SLUG = "django_boilerplate"

# Files that must exist in the rendered project tree (static, from template).
EXPECTED_FILES = [
    ".editorconfig",
    ".env.example",
    ".gitignore",
    ".pre-commit-config.yaml",
    "AGENTS.md",
    "gunicorn_start",
    "LICENSE",
    "Makefile",
    "pyproject.toml",
    "README.md",
    "supervisor.conf",
    f"{DEFAULT_SLUG}/manage.py",
    f"{DEFAULT_SLUG}/config/__init__.py",
    f"{DEFAULT_SLUG}/config/settings.py",
    f"{DEFAULT_SLUG}/config/urls.py",
    f"{DEFAULT_SLUG}/config/wsgi.py",
    f"{DEFAULT_SLUG}/config/asgi.py",
    "tests/__init__.py",
    "tests/test_smoke.py",
    ".github/workflows/test.yml",
]

# Files generated by the post-gen hook (git init + uv sync + pre-commit).
EXPECTED_GENERATED_FILES = [
    ".env",
    "uv.lock",
    "requirements.txt",
    "requirements-dev.txt",
]

# Files that must NOT exist — removed in the packaging modernisation.
OBSOLETE_FILES = [
    "Pipfile",
    "Pipfile.lock",
    ".flake8",
    ".isort.cfg",
    "setup_env.sh",
    # Note: readme.md → README.md rename is verified by README.md in EXPECTED_FILES.
    # macOS APFS is case-insensitive so asserting readme.md is absent would always
    # fail when README.md exists.
]


def _run(cmd: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        cmd, cwd=cwd, env=_ISOLATED_ENV, capture_output=True, text=True
    )


# ---------------------------------------------------------------------------
# Basic bake
# ---------------------------------------------------------------------------


def test_default_bake_succeeds(cookies):
    """Bake with default inputs; assert no errors."""
    result = cookies.bake()

    assert result.exit_code == 0, result.exception
    assert result.exception is None
    assert result.project_path.is_dir()


def test_expected_files_present(cookies):
    """Every expected file exists in the rendered tree."""
    result = cookies.bake()

    assert result.exit_code == 0, result.exception
    for relpath in EXPECTED_FILES:
        assert (result.project_path / relpath).exists(), f"missing: {relpath}"


def test_generated_files_present(cookies):
    """Files written by the post-gen hook (uv sync + pre-commit) are present."""
    result = cookies.bake()

    assert result.exit_code == 0, result.exception
    for relpath in EXPECTED_GENERATED_FILES:
        assert (result.project_path / relpath).exists(), f"missing: {relpath}"


def test_obsolete_files_not_present(cookies):
    """Legacy files removed during packaging modernisation are absent."""
    result = cookies.bake()

    assert result.exit_code == 0, result.exception
    for relpath in OBSOLETE_FILES:
        assert not (result.project_path / relpath).exists(), f"unexpected: {relpath}"


# ---------------------------------------------------------------------------
# Variable rendering
# ---------------------------------------------------------------------------


def test_custom_slug_renders(cookies):
    """project_name drives slug derivation; project_path reflects the slug."""
    result = cookies.bake(extra_context={"project_name": "My Django App"})

    assert result.exit_code == 0, result.exception
    assert result.project_path.name == "my_django_app_project"


@pytest.mark.parametrize("python_version", ["3.10", "3.11", "3.12"])
def test_python_version_renders_in_pyproject(cookies, python_version):
    """pyproject.toml requires-python reflects the chosen python_version."""
    result = cookies.bake(extra_context={"python_version": python_version})

    assert result.exit_code == 0, result.exception
    pyproject = (result.project_path / "pyproject.toml").read_text()
    assert f'requires-python = ">={python_version}"' in pyproject


def test_author_renders_in_pyproject(cookies):
    """author_name and author_email appear in the generated pyproject.toml."""
    result = cookies.bake(
        extra_context={
            "author_name": "Jane Dev",
            "author_email": "jane@example.com",
        }
    )

    assert result.exit_code == 0, result.exception
    pyproject = (result.project_path / "pyproject.toml").read_text()
    assert "Jane Dev" in pyproject
    assert "jane@example.com" in pyproject


def test_env_file_has_secret_key(cookies):
    """The post-gen hook writes .env with a real DJANGO_SECRET_KEY (not placeholder)."""
    result = cookies.bake()

    assert result.exit_code == 0, result.exception
    env_content = (result.project_path / ".env").read_text()
    assert "DJANGO_SECRET_KEY=" in env_content
    assert "changeme" not in env_content


# ---------------------------------------------------------------------------
# Generated project quality
# ---------------------------------------------------------------------------


def test_generated_project_passes_ruff(cookies):
    """Run `uv run ruff check .` in the baked project; expect exit 0."""
    result = cookies.bake()

    assert result.exit_code == 0, result.exception
    proc = _run(["uv", "run", "ruff", "check", "."], result.project_path)
    assert proc.returncode == 0, f"ruff failed:\n{proc.stdout}\n{proc.stderr}"


def test_generated_project_passes_pytest(cookies):
    """Run `uv run pytest` in the baked project; expect exit 0."""
    result = cookies.bake()

    assert result.exit_code == 0, result.exception
    proc = _run(["uv", "run", "pytest"], result.project_path)
    assert proc.returncode == 0, f"pytest failed:\n{proc.stdout}\n{proc.stderr}"


def test_requirements_files_have_content(cookies):
    """requirements.txt (prod) and requirements-dev.txt (all) are non-empty.

    The uv-export pre-commit hooks write these files when the post-gen hook
    runs `pre-commit run --all-files`. requirements-dev.txt is a strict
    superset of requirements.txt.
    """
    result = cookies.bake()

    assert result.exit_code == 0, result.exception
    req = (result.project_path / "requirements.txt").read_text()
    req_dev = (result.project_path / "requirements-dev.txt").read_text()

    # Django must appear in both (it's a runtime dep).
    assert "django" in req.lower()
    assert "django" in req_dev.lower()
    # ruff is a dev-only dep — must appear in requirements-dev.txt but not requirements.txt.
    assert "ruff" in req_dev.lower()
    assert "ruff" not in req.lower()


# ---------------------------------------------------------------------------
# Post-gen hook: requires uv
# ---------------------------------------------------------------------------


def test_post_gen_hook_requires_uv(tmp_path):
    """Hook exits non-zero with a friendly message when uv is not on PATH."""
    hook_path = Path(__file__).parent / "hooks" / "post_gen_project.py"

    # Replace the Jinja token (unrendered on disk) with a valid Python literal.
    rendered = hook_path.read_text().replace(
        "{{cookiecutter.project_slug | tojson}}", '"test_project"'
    )
    test_hook = tmp_path / "post_gen_project.py"
    test_hook.write_text(rendered)

    proc = subprocess.run(
        [sys.executable, str(test_hook)],
        cwd=tmp_path,
        env={"PATH": "/usr/bin:/bin", "HOME": str(tmp_path)},
        capture_output=True,
        text=True,
    )

    assert proc.returncode != 0
    assert "uv" in proc.stderr.lower()


# ---------------------------------------------------------------------------
# CI workflow: copy_without_render
# ---------------------------------------------------------------------------


def test_github_workflow_copied_verbatim(cookies):
    """The inner .github/ is in _copy_without_render — GitHub Actions ${{ }} expressions
    must survive unchanged, not be mangled by Jinja2 rendering."""
    result = cookies.bake()

    assert result.exit_code == 0, result.exception
    workflow = (result.project_path / ".github/workflows/test.yml").read_text()
    # These GitHub Actions expression tokens would be wiped if Jinja processed the file.
    assert "${{ github.workflow }}" in workflow
    assert "${{ matrix.python-version }}" in workflow


# ---------------------------------------------------------------------------
# Pre-gen hook: input validation
# ---------------------------------------------------------------------------


def test_invalid_slug_rejected(cookies):
    """A project_name producing a leading-digit slug fails the pre-gen hook."""
    # "1bad start" → slug "1bad_start" — not a valid Python identifier.
    result = cookies.bake(extra_context={"project_name": "1bad start"})

    assert result.exit_code != 0


def test_python_keyword_slug_rejected(cookies):
    """A slug equal to a Python reserved keyword is rejected."""
    result = cookies.bake(extra_context={"project_slug": "class"})

    assert result.exit_code != 0


def test_unsafe_chars_in_project_name_rejected(cookies):
    """Quotes in project_name break generated TOML — rejected by pre-gen hook."""
    result = cookies.bake(extra_context={"project_name": 'Bad"Name'})

    assert result.exit_code != 0


def test_unsafe_chars_in_author_name_rejected(cookies):
    """Quotes in author_name break generated pyproject.toml."""
    result = cookies.bake(extra_context={"author_name": 'Bad"Name'})

    assert result.exit_code != 0


def test_newline_in_author_name_rejected(cookies):
    result = cookies.bake(extra_context={"author_name": "Line\nTwo"})

    assert result.exit_code != 0


def test_invalid_email_rejected(cookies):
    result = cookies.bake(extra_context={"author_email": "not-an-email"})

    assert result.exit_code != 0


def test_email_with_quote_rejected(cookies):
    """Quotes in email local-part must be rejected for clean TOML output."""
    result = cookies.bake(extra_context={"author_email": 'b"d@example.com'})

    assert result.exit_code != 0


def test_non_ascii_author_accepted(cookies):
    """Non-ASCII characters in author_name are valid — only TOML-unsafe chars blocked.

    |tojson renders non-ASCII as unicode escapes (ASCII-safe JSON), so the raw
    TOML contains e.g. "Ren\\u00e9e" rather than the literal é glyph. Both are
    valid TOML; we check the ASCII suffix to avoid encoding ambiguity.
    """
    result = cookies.bake(extra_context={"author_name": "Renée Dupont"})

    assert result.exit_code == 0, result.exception
    pyproject = (result.project_path / "pyproject.toml").read_text(encoding="utf-8")
    # "Dupont" is unique to this author; é is escaped but the ASCII suffix is not.
    assert "Dupont" in pyproject
